feat: extract CodegenEngine
awslabs/smithy-dafny pull request #212
Opened 2023-03-30 20:30 UTC by alex-chew

*Issue #, if available:* #151 (partial)

*Description of changes:* Extracts the codegen management logic from `CodegenCli` into a `CodegenEngine`, so that both `CodegenCli` and the `smithy-dafny-codegen` plugin serve as thin entrypoints to `CodegenEngine`. The `CodegenCli` interface is not expected to change.

TODO:

- [x] Fix SQS TestModel Gradle configuration so it can build
- [x] Generate csproj file
- ~~Generate Makefile~~ (will add as fast-follow)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-03-31 20:15 UTC, robin-aws requested changes
I still have to have a closer look at the core CodegenEngine, but otherwise this looks great aside from these comments.

2023-03-31 20:56 UTC, texastony requested changes
Publishing an incomplete review.
Will review from a scratch when this PR is moved out of draft.

2023-03-31 23:08 UTC, robin-aws reviewed
LGTM aside from a couple of small nits

2023-04-01 01:47 UTC, texastony submitted a review, later dismissed

2023-04-05 00:01 UTC, robin-aws approved these changes

2023-04-05 02:10 UTC, texastony approved these changes

2023-04-05 04:32 UTC, merged