chore: address lints in SimpleString Rust
awslabs/smithy-dafny pull request #343
Opened 2024-04-19 20:09 UTC by andrewbanchich

*Description of changes:*

- add `#![allow(deprecated)]` to silence warning for matching on deprecated `GetStringUTF8Error::Unhandled` enum variant
- remove unused `use core::panic;` import
- format with `rustfmt`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-04-26 18:14 UTC, robin-aws requested changes
Great first start! Just one change to make.

2024-04-26 18:14 UTC, robin-aws commented on TestModels/SimpleTypes/SimpleString/runtimes/rust/dafny_impl/Cargo.lock
AFAICT the best practice is usually to commit `Cargo.lock` for binaries, but not for libraries, since the actual dependency resolution happens in consuming projects instead. So I think we should not commit this file.

2024-05-02 13:24 UTC, andrewbanchich commented on TestModels/SimpleTypes/SimpleString/runtimes/rust/dafny_impl/Cargo.lock
updated!

2024-05-02 16:39 UTC, robin-aws approved these changes
🚀

2024-05-02 16:40 UTC, merged