chore(tests): Add lite versions of DDB and KMS test models
awslabs/smithy-dafny pull request #469
Opened 2024-07-03 18:30 UTC by robin-aws

…idiom

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-08 18:06 UTC, texastony commented on TestModels/aws-sdks/ddb-lite/build.gradle.kts
> +tasks["jar"].enabled = false
Question/Confusion: the Jar is disabled if this is uncommented.
So if you commented it, would that enable the Jar?

2024-07-08 18:06 UTC, texastony commented on TestModels/aws-sdks/kms-lite/build.gradle.kts
> +
Also wrong or confusing.

2024-07-08 18:06 UTC, texastony commented on TestModels/aws-sdks/kms-lite/smithy-build.json
> +            "selector": "operation :not([id|name = GenerateDataKey, Encrypt, Decrypt, GenerateDataKeyWithoutPlaintext, ReEncrypt])"
@josecorella do we need another Operation for ECDH?

Not that this is directly influences Smithy-Dafny or the correctness of this PR,
but I like some consistency;
I fear that we might copy and paste and fail...

2024-07-08 18:06 UTC, texastony commented on TestModels/aws-sdks/kms-lite/test/TestComAmazonawsKms.dfy
Issue/Non-Blocking: Oh... this is third copy of this file to be checked in.
There is one in the MPL proper, one for the "heavy" test model, and one here.
Damn shame we have not figured out to reference identical files via Symbolic Links or some such.

2024-07-08 18:24 UTC, robin-aws commented on TestModels/aws-sdks/kms-lite/smithy-build.json
> +            "selector": "operation :not([id|name = GenerateDataKey, Encrypt, Decrypt, GenerateDataKeyWithoutPlaintext, ReEncrypt])"
I agree and the point of this list was to make what MPL needs, so I'd prefer to get it right even if it doesn't affect the validity of the PR.

2024-07-08 18:26 UTC, robin-aws commented on TestModels/aws-sdks/ddb-lite/build.gradle.kts
> +tasks["jar"].enabled = false
Ah that's from the Smithy Gradle plugin template, agreed it's just confusing to leave it in when we never ship jars with just Smithy models in them around. Removed it from these models and `sqs` where it originally snuck in.

2024-07-08 18:27 UTC, robin-aws commented on TestModels/aws-sdks/kms-lite/test/TestComAmazonawsKms.dfy
IKR, I had the same thought. `include`-ing a test file from a different test model would just pull in all the conflicting Dafny code. But I preferred to make sure these tests still worked on the projected model, and duplication across test models doesn't keep me up at night as much as many other things. :)

2024-07-08 18:37 UTC, texastony commented on TestModels/aws-sdks/kms-lite/smithy-build.json
> +            "selector": "operation :not([id|name = GenerateDataKey, Encrypt, Decrypt, GenerateDataKeyWithoutPlaintext, ReEncrypt])"
> DeriveSharedSecret and GetPublicKey are the ones used for ecdh

From an older Slack DM with @josecorella

2024-07-08 20:17 UTC, seebees commented on TestModels/aws-sdks/kms-lite/model/model.json
I would use the 2.0 version from https://github.com/aws/aws-cryptographic-material-providers-library/blob/main/ComAmazonawsKms/Model/kms/model.json

2024-07-08 20:20 UTC, seebees requested changes
Can we add the 2 operations and update the Smithy version?

2024-07-08 20:20 UTC, seebees commented on TestModels/aws-sdks/kms-lite/model/model.json
I would use the 2.0 version from here: 

https://github.com/aws/aws-cryptographic-material-providers-library/blob/main/ComAmazonawsKms/Model/kms/model.json

2024-07-08 20:20 UTC, seebees commented on TestModels/aws-sdks/kms-lite/smithy-build.json
> +            "selector": "operation :not([id|name = GenerateDataKey, Encrypt, Decrypt, GenerateDataKeyWithoutPlaintext, ReEncrypt])"
```suggestion
            "selector": "operation :not([id|name = GenerateDataKey, Encrypt, Decrypt, GenerateDataKeyWithoutPlaintext, ReEncrypt, DeriveSharedSecret, GetPublicKey])"
```

2024-07-08 22:09 UTC, seebees approved these changes, later dismissed
LGTM

2024-07-09 03:30 UTC, seebees approved these changes
LGTM

2024-07-09 03:39 UTC, merged