fix: use nullable types for all structure members (Java, .NET)
awslabs/smithy-dafny pull request #496
Opened 2024-07-26 01:09 UTC by alex-chew

*Issue #, if available:* #278

*Description of changes:* Changes the .NET and Java code generators to use nullable types for all structure members (even required members with primitive-equivalent shapes).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-08-12 17:55 UTC, alex-chew commented
Marking this as ready for review despite the unrelated failing CI test (something to do with a Rust-related patch not applying, which we believe is due to unintended nondeterminism in the module order emitted by the Dafny-to-Rust compiler).

2025-01-06 18:25 UTC, robin-aws requested changes
Leaving an initial blocking review just because I'm not worried that this isn't correct for Smithy 1.0 models, that the better fix is to support @box consistently (it is supported for Java but not .NET AFAICT)

2025-01-14 20:42 UTC, texastony commented
An issue with going to down further down this path is that Smithy-Dafny is forking the Smithy 1.0 Specification.

Smithy-Dafny could argue that such a change in behavior is necessary to support the Local Service Trait; 
but I am not certain that argument is valid,
as I think the Local Service Trait can work without this forking of behavior.

A stronger argument, in favor of the box approach, 
or maybe just in dropping Smithy 1.0 and upgrading to 2.0,
is that all Smithy Code Generators should behave same by following the Smithy Specification.

2025-02-14 17:43 UTC, robin-aws commented
> An issue with going to down further down this path is that Smithy-Dafny is forking the Smithy 1.0 Specification.
> 
> Smithy-Dafny could argue that such a change in behavior is necessary to support the Local Service Trait; but I am not certain that argument is valid, as I think the Local Service Trait can work without this forking of behavior.
> 
> A stronger argument, in favor of the box approach, or maybe just in dropping Smithy 1.0 and upgrading to 2.0, is that all Smithy Code Generators should behave same by following the Smithy Specification.

I agree this deviation isn't related to local services. I suspect it's just that we misinterpreted the Smithy 1.0 semantics everywhere but Java.

Tactically though, given all the existing smithy-dafny models are currently relying on this misinterpretation, I say it's better to align Java and .NET with the models' intent and how they work in the other languages. We should document this explicitly as a smithy-dafny difference for now as part of this PR as well. 

Beyond that, we should ensure smithy-dafny DOES align with Smithy semantics on Smithy 2.0 models.

2025-02-16 00:27 UTC, texastony commented on codegen/smithy-dafny-codegen/src/main/java/software/amazon/polymorph/smithyjava/nameresolver/Native.java
> +        DOUBLE -> NATIVE_TYPES_BY_SIMPLE_SHAPE_TYPE.get(shape.getType());
I knew I had written logic to handle this!
If I only Smithy-2.0 had been published earlier... 
I literally quoted the Smithy-1.0 spec...

2025-02-26 00:40 UTC, robin-aws approved these changes
My only comment was going to be that a bit more testing would be good, but then I recalled that I had to hamstring my smokeTests test on Constraints due to this issue. Now that it's fixed I was able to push a commit to remove the workaround, which addresses my concern about testing coverage, so I'm happy! :)

2025-02-26 01:00 UTC, merged