feat: enable ddbv2 support
awslabs/smithy-dafny pull request #663
Opened 2024-10-24 01:12 UTC by ShubhamChaturvedi7

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-24 23:25 UTC, robin-aws requested changes

2024-10-24 23:25 UTC, robin-aws commented on TestModels/aws-sdks/ddbv2/codegen-patches/dotnet/dafny-4.8.0.patch
FYI you don't need this file, patch files apply to all dafny versions at or above the named version automatically

2024-10-24 23:25 UTC, robin-aws commented on TestModels/aws-sdks/kmsv2/runtimes/java/build.gradle.kts
FYI if you add `POLYMORPH_OPTIONS=--generate project-files` to the Makefile the `java` and `net` project files will be generated for you, so you don't have to check these in.

You can do `--generate client-constructors` too for DDB, but that doesn't work for KMS since we've added the extra `RegionMatch` method.

2024-10-24 23:25 UTC, robin-aws commented on TestModels/aws-sdks/ddbv2/Model/model.json
Make sure you document why we do this really well in the README

2024-10-24 23:25 UTC, robin-aws commented on TestModels/dafny-dependencies/Model/aws.test.smithy
What's this for?

2024-10-24 23:25 UTC, robin-aws commented on TestModels/aws-sdks/ddbv2/runtimes/net/.editorconfig
Intentional checkin?

2024-10-24 23:28 UTC, ShubhamChaturvedi7 commented on TestModels/aws-sdks/ddbv2/codegen-patches/dotnet/dafny-4.8.0.patch
Nice! Removed.

2024-10-24 23:31 UTC, ShubhamChaturvedi7 commented on TestModels/dafny-dependencies/Model/aws.test.smithy
It's a trait used by the ddbv2 model - I was thinking to remove it but realized @texastony had this in his commit so I might as well pull it. Brings us one more step closer to full model support.

There's also a chance that we might be able to pull this using maven or something.

2024-10-24 23:31 UTC, ShubhamChaturvedi7 commented on TestModels/aws-sdks/ddbv2/runtimes/net/.editorconfig
Yeah - was present in ddb v1. So checked in here since this is not in the list of ignored files.

2024-10-24 23:45 UTC, robin-aws commented on TestModels/dafny-dependencies/Model/aws.test.smithy
Ah okay, the cleaner way to pull it in is to add the appropriate dependency here: https://github.com/smithy-lang/smithy-dafny/blob/main-1.x/codegen/smithy-dafny-codegen/build.gradle.kts#L23

Note one advantage of the Smithy build plugin over the polymorph CLI is the former lets the Smithy project define these dependencies.

2024-10-25 00:22 UTC, texastony commented on TestModels/aws-sdks/ddbv2/runtimes/net/.editorconfig
`.editorconfig` were my early attempt at getting .NET formatting and to ignore a bunch of errors.

Because .NET is so noisy.

2024-10-25 00:27 UTC, texastony commented on TestModels/dafny-dependencies/Model/aws.test.smithy
I tried to remove the tests from the model,
but could not get it to work,
so I checked it in.

If we refactor the MPL/DB-ESDK/ESDK to use the Smithy Build Plugin,
then we can do as you say.

Otherwise, we should probably just check in this test file.
At least in the MPL.

2024-10-25 20:45 UTC, ShubhamChaturvedi7 commented on TestModels/dafny-dependencies/Model/aws.test.smithy
I think maven dependency should work for MPL as well.

2024-10-25 20:45 UTC, ShubhamChaturvedi7 commented on TestModels/aws-sdks/kmsv2/runtimes/java/build.gradle.kts
`POLYMORPH_OPTIONS=--generate project-files --generate client-constructors`
both of them cause more problems than they solve. The project-files doesn't use the right dependencies so the code will never compile unless we use another patch. client-constructors  modifies the Index.dfy which breaks the sed magic.

2024-10-25 20:58 UTC, ShubhamChaturvedi7 commented on TestModels/aws-sdks/ddbv2/Model/model.json
Added line explaining why are we doing this.

2024-10-28 19:34 UTC, robin-aws commented on TestModels/dafny-dependencies/Model/aws.test.smithy
I can live with this for now

2024-10-28 19:34 UTC, robin-aws approved these changes

2024-10-28 19:36 UTC, texastony commented on TestModels/dafny-dependencies/Model/aws.test.smithy
@ShubhamChaturvedi7 Alas, it will not, as the MPL does not use the Smithy Build Plugin.

2024-10-28 19:47 UTC, ShubhamChaturvedi7 commented on TestModels/dafny-dependencies/Model/aws.test.smithy
I think the context for Robin's smithy-build-plugin and yours is different. I think Robin meant that you can configure per project dependency IF we were using smithy-build. But what I'm doing is adding it to the codegen project. So it should work regardless if it's CLI or smithy-build.

2024-10-28 19:47 UTC, merged