feat: smithy-go TestModels
awslabs/smithy-dafny pull request #735
Opened 2024-12-02 20:38 UTC by ShubhamChaturvedi7

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-12-02 21:55 UTC, robin-aws commented on TestModels/Constructor/runtimes/go/TestsFromDafny-go/go.mod
> +//TODO: Drop this after Dafny fixes the https://t.corp.amazon.com/P150784381
Ticket is resolved already :)

2024-12-04 02:06 UTC, robin-aws requested changes
Love the increased testing coverage sneaking in! Don't love having to define so many additional variables and files, but a lot of it is much easier to fix once I switch things over to a Gradle-based build system. I have questions about what's being checked in but I'm not going to block hard on them unless it looks easy to avoid them.

2024-12-04 02:06 UTC, robin-aws commented on TestModels/dafny-dependencies/StandardLibrary/runtimes/go/ImplementationFromDafny-go/UTF8/externs.go
> +			r = append(r, uint16(val.(dafny.Char)))
Will Go's `append` function allocate just one more character each time, or does it do something like doubling the size of the slice so that this pattern isn't too slow?

2024-12-04 02:06 UTC, robin-aws commented on TestModels/aws-sdks/kmsv2/Makefile
> +
Are these new variables required on all libraries, even if they don't want to build to Go? I can live with requiring a ton of boilerplate for now, but it's important that existing smithy-dafny projects don't break, especially in the weird and wonderful ways the makefile code tends to, if they don't define the new variables.

2024-12-04 02:06 UTC, robin-aws commented on TestModels/aws-sdks/kms/removeDotFromExtern.sh
This script could be under the top level `scripts` directory instead of copied into every test model that needs it, I hope?

2024-12-04 02:06 UTC, robin-aws commented on TestModels/aws-sdks/ddbv2/runtimes/go/ImplementationFromDafny-go/DynamoDBwrapped/shim.go
Why are all these shim.go files checked in?

2024-12-04 02:06 UTC, robin-aws commented on TestModels/aws-sdks/ddb/runtimes/go/TestsFromDafny-go/go.sum
Is it standard Go practice for these checksum files to be checked in?

2024-12-04 02:06 UTC, robin-aws commented on TestModels/SimpleTypes/SimpleBoolean/Makefile
> +GO_MODULE_NAME="github.com/smithy-lang/smithy-dafny/TestModels/SimpleTypes/SimpleBoolean"
This seems like it could be defined once in `TestModels/SharedMakefile.mk` instead, something like `GO_MODULE_NAME="github.com/smithy-lang/smithy-dafny/$THIS_RELATIVE_DIR"

2024-12-04 02:06 UTC, robin-aws commented on TestModels/CodegenPatches/Model/SimpleCodegenpatchesTypes.dfy
> +    | Opaque(obj: object, alt_text : string)
I think this is wrong given the current state of mainline, but I think the CI should tell you that anyway

2024-12-04 22:14 UTC, ShubhamChaturvedi7 commented on TestModels/Constructor/runtimes/go/TestsFromDafny-go/go.mod
> +//TODO: Drop this after Dafny fixes the https://t.corp.amazon.com/P150784381
Fixed this and upgraded to 4.9.1

2024-12-04 22:14 UTC, ShubhamChaturvedi7 commented on TestModels/dafny-dependencies/StandardLibrary/runtimes/go/ImplementationFromDafny-go/UTF8/externs.go
> +			r = append(r, uint16(val.(dafny.Char)))
Doubles the size.

2024-12-04 22:15 UTC, ShubhamChaturvedi7 commented on TestModels/aws-sdks/kmsv2/Makefile
> +
No this is only required to build libraries to Go.

2024-12-04 22:16 UTC, ShubhamChaturvedi7 commented on TestModels/aws-sdks/ddb/runtimes/go/TestsFromDafny-go/go.sum
Yup, otherwise you'll be forced to run `go get / go mod tidy` on every pull.

2024-12-04 22:20 UTC, ShubhamChaturvedi7 commented on TestModels/SimpleTypes/SimpleBoolean/Makefile
> +GO_MODULE_NAME="github.com/smithy-lang/smithy-dafny/TestModels/SimpleTypes/SimpleBoolean"
I do not want to prematurely optimize it. It's an attribute of the individual projects and follows from go convention that you always fully define the module name even if you are inside another module.

2024-12-04 22:25 UTC, ShubhamChaturvedi7 commented on TestModels/CodegenPatches/Model/SimpleCodegenpatchesTypes.dfy
> +    | Opaque(obj: object, alt_text : string)
Ideally this file shouldn't be present at all. But in any case a pull from main should fix this. I pull once in a while from main - and this is the final PR before enabling CI, I want to wait till then.

2024-12-04 22:28 UTC, ShubhamChaturvedi7 commented on TestModels/aws-sdks/kms/removeDotFromExtern.sh
This is not required and I had cleaned up most of them. Cleaned up whatever was missed.

2024-12-04 22:31 UTC, ShubhamChaturvedi7 commented on TestModels/aws-sdks/ddbv2/runtimes/go/ImplementationFromDafny-go/DynamoDBwrapped/shim.go
Many of them needs to be checked in because of https://t.corp.amazon.com/0150b5ed-387c-4669-8ce8-324c5c6fa6a1/communication#b37365a7-1e22-46d3-8f6a-2e783d683232 

But this was not required and removed it.

2024-12-04 22:51 UTC, robin-aws commented on TestModels/SimpleTypes/SimpleBoolean/Makefile
> +GO_MODULE_NAME="github.com/smithy-lang/smithy-dafny/TestModels/SimpleTypes/SimpleBoolean"
True, I'm just saying it looks like it is derivable from conventions. But hopefully that can be improved later.

2024-12-04 22:54 UTC, robin-aws approved these changes

2024-12-04 23:14 UTC, merged