feat: Generate KMS client using AWS SDK for Java V2
awslabs/smithy-dafny pull request #82
Opened 2022-12-21 22:05 UTC by lucasmcdonald3

*Issue #, if available:*

*Description of changes:*

* Generate a KMS client that uses AWS SDK for Java V2. 
* Refactor code between SDKs V1/V2.

*Testing:*

Ran `bin/generate-code.sh` from the most recent commit off of my [private-aws-encryption-sdk-dafny-staging fork](https://github.com/lucasmcdonald3/private-aws-encryption-sdk-dafny-staging/tree/v4-java-dev-kms-v2). Then, ran `compile_java && make test_java`, which ran a decrypt smoke test which succeeded.

I also tested there's no regression to V1 KMS client by generating V1 code and running the same tests.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-12-22 03:29 UTC, seebees requested changes
Not really a change:
Can you open a PR the AWS SDK KMS project with SDK style v2.
And then link to the tests passing for that plz :)

2022-12-22 17:11 UTC, texastony requested changes

2022-12-22 18:39 UTC, texastony requested changes

2023-02-13 20:46 UTC, texastony reviewed
Groovy. 
@lucasmcdonald3 I am going to fork this branch,
resolve some nitpicks and questions I left here,
and run with it.

2023-03-31 20:16 UTC, closed without merging